# Generated by Django 5.0.1 on 2024-01-05 15:04

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_alter_blog_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='desciption',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
