# Generated by Django 5.0.1 on 2024-01-05 16:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_alter_blog_desciption'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rate',
            old_name='coment',
            new_name='comment',
        ),
    ]
